#!/bin/bash 

# Copyright 2016 Crunchy Data Solutions, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eouf pipefail

echo "starting pgbench load test..."

./init-tests
psql -h $MASTER_HOST -p $MASTER_PORT -U $PG_USER -c 'create table proxytest (id int, name varchar(20), value varchar(20));' $DATABASE

echo "starting crunchy-proxy"
killall crunchy-proxy || true
./crunchy-proxy start --config=config.yaml&

echo "start the concurrency test..."

pgbench \
	-h $PROXY_HOST \
	-p $PROXY_PORT \
	-U $PG_USER \
	-f concurrency-test.sql \
	-c 4 \
	-t 100 $DATABASE

echo "concurrency test ends."
